### ISSUE TITLE
 API decommisioned

### ISSUE THREAD

**Issue by expaso** [xirixiz/afvaldienst#2]
For reference: json.mijnafvalwijzer.nl was decommisioned (as you already know).

Perhaps you can simply replace URL with:

https://api.mijnafvalwijzer.nl/webservices/appsinput/?apikey=xxxx&method=postcodecheck&postcode=6686CG&street=&huisnummer=1&toevoeging=&app_name=afvalwijzer&platform=phone&mobiletype=android&afvaldata=2020-09-13&version=58&langs=nl

This is the way the android app fetched it's data. 
The API key is a fixed string (client secret) that is the same over all app installations.

**Comment by expaso** [comment]
@xirixiz Thanks for your quick fix! Everything is working like a charm! 
Fijn weekend!

**Comment by xirixiz** [comment]
Goodmorning, 

I just received the message below from mijnafvalwijzer.nl. I don't want to have discussions about this with mijnafvalwijzer.nl so I decided to remove the api and url information from the component. I asked them whether is possible to come up with a solution so everyone is happy. I`ll inform you when I received a reply.

----

Ik heb begrepen dat jij de ontwikkelaar bent achter een aantal projecten die op Github staan t.a.v. home-automation en data-fetching vanuit ons product 'Mijn Afvalwijzer'. 

Voorheen was deze API publiekelijk beschikbaar via 'JSON.mijnafvalwijzer.nl'. Dit is inmiddels niet meer het geval en de API is publiekelijk niet meer beschikbaar. Om onze Apps te laten communiceren met de backend (de API.mijnafvalwijzer.nl) wordt gebruik gemaakt van een API-key. Deze key is klaarblijkelijk via reverse-engineering, of data-sniffing uit de app gehaald en wordt nu misbruikt om toegang tot de API te krijgen. De key is specifiek bedoelt om oneigenlijk toegang tot de dienst tegen te gaan.

Dit is niet de bedoeling. We willen je dan ook vriendelijk vragen de betreffende code (waar deze key gebruikt wordt) offline te halen. We zullen na een korte periode deze API-key sowieso gaan aanpassen en daarmee stopt de werking van de plugin. We begrijpen dat dit vervelend kan zijn voor diegene die home-automation gebruiken. Wellicht biedt de betreffende gemeente zelf een oplossing om deze data (publiekelijk) te benaderen.

**Comment by xirixiz** [comment]
... L2... https://github.com/xirixiz/python-afvalwijzer-afvalstoffendienst/blob/737b636fcee71049bf54e15adb48fda8d33112a6/.gitignore

**Comment by expaso** [comment]
Oh snif. Unfortunately, they give no reasoning for why this data is not available anymore.
Possibly it's because they fear a lot of API calls, but then again, reverting to a scraper would cost a lot more bandwidth.

**Comment by expaso** [comment]
Thanks @xirixiz! Back to a scraper I see.. Impressive to see how quickly you fixed this!

So.. to recap this bizarre incident:

This said IT-company was hired by half of our city's to **distribute** garbage collection data. 
When we use that data they close down the API and reply:
" Wellicht biedt de betreffende gemeente zelf een oplossing om deze data (publiekelijk) te benaderen."
Uhm.. that was YOUR job, remember... That's exactly what you were hired for in the first place!

So, now we reverted back to a scraper, basically fetching the same data, and suddenly all is green?

You can carry me away.. we're talking about garbage collection days right?
Better make sure this 'secret information' does not fall into the wrong hands 😂🤣

**Comment by xirixiz** [comment]
@Expaso really weird indeed, I fully agree with you. This is limiting something without thinking it through what is actually happening.

- Trash data is freely accessible within the app
- Trash data is freely accessible at their website
- Trash data is freely accessible at the website of the community your living in
- Trash data doesn't contain any personal information

...and still we're not allowed to use their api. I explained this to the guy I spoke from security, but he didn't listen, and just said it isn't allowed at this moment, period! But I agree partially with this, as we don't want this data to be obtained by the Russians, Americans and/or Chinese 🤣
