### ISSUE TITLE
API Token documentation

### ISSUE THREAD

**Issue by Smiggel** [xirixiz/afvaldienst#3]
Can you update the documentation on where to get the api token?

**Comment by xirixiz** [comment]
Unfortunately Im not allowed to from the provider(s), therefor I had to remove it from the source...

**Comment by P-Verbrugge** [comment]
Is there any way to register for a token? Or is it closed for everyone? Have the same problem. :-)

**Comment by xirixiz** [comment]
Unfortunately closed for everyone...

**Comment by P-Verbrugge** [comment]
Too bad. :-(

**Comment by xirixiz** [comment]
... L2... https://github.com/xirixiz/python-afvalwijzer-afvalstoffendienst/blob/737b636fcee71049bf54e15adb48fda8d33112a6/.gitignore
